#pragma once

#define CROGUE_VERSION_MAJOR 0
#define CROGUE_VERSION_MINOR 1
#define CROGUE_VERSION_PATCH 0

#ifdef DEBUG
#define CROGUE_VERSION_TAG "-debug"
#else
#define CROGUE_VERSION_TAG ""
#endif

#define CROGUE_STRINGIFY_(x) #x
#define CROGUE_STRINGIFY(x) CROGUE_STRINGIFY_(x)

// as string
#define CROGUE_VERSION_STRING                  \
        CROGUE_STRINGIFY(CROGUE_VERSION_MAJOR) \
        "." CROGUE_STRINGIFY(CROGUE_VERSION_MINOR) "." CROGUE_STRINGIFY(CROGUE_VERSION_PATCH) CROGUE_VERSION_TAG
